name: 113_SumTask
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10.6
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - pip
  - pip:
    - git+https://github.com/huggingface/transformers@v4.24.0
    - datasets
    - sentencepiece
    - protobuf==3.20.*
    - openai
    - rouge
    - bert_score
